server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: sapassword1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10 # buffer size 10
        failure-rate-threshold: 50 #
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true # half open enabled
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10 # record the outcome of calls when the CircuitBreaker is closed
        sliding-window-type: COUNT_BASED # the type of the sliding window
#  retry:
#    instances:
#      orderService: # Tên của Retry dành riêng cho Order Service
#        maxAttempts: 4 # Số lần thử lại tối đa (3 lần thử lại + 1 lần gọi ban đầu)
#        waitDuration: 5s # Thời gian chờ giữa các lần thử lại (5 giây)
#        retryExceptions: # Danh sách các exception kích hoạt retry
#          - org.springframework.web.client.HttpServerErrorException # Lỗi server
#          - java.net.ConnectException # Lỗi không thể kết nối (khi service down)
#          - java.util.concurrent.TimeoutException # Lỗi timeout
#
#  ratelimiter:
#    instances:
#      orderServiceRateLimiter: # Tên của Rate Limiter
#        limitForPeriod: 5 # Giới hạn 5 yêu cầu trong một khoảng thời gian
#        limitRefreshPeriod: 1m # Làm mới giới hạn sau mỗi phút
#        timeoutDuration: 0 # Không chờ đợi để có được giấy phép

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

jwt:
  secret: mySecretKey
